# Generated by Django 4.1.4 on 2023-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
