# Generated by Django 4.1.4 on 2023-04-23 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_newuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='username',
        ),
        migrations.AddField(
            model_name='newuser',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='accounts.newuser'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='age',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
