# Generated by Django 4.1.4 on 2023-04-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_newuser_date_joined_remove_newuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
