# Generated by Django 4.1.4 on 2023-04-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patient_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='stage',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_phone',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
