# Generated by Django 4.1.4 on 2023-04-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_disease_stage_alter_patient_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='stage',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_phone',
            field=models.CharField(max_length=12),
        ),
    ]
