# Generated by Django 4.1.4 on 2023-04-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(max_length=12)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.newuser')),
            ],
        ),
    ]
