# Generated by Django 4.1.4 on 2023-04-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
