# Generated by Django 4.1.4 on 2023-04-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='accounts.patient'),
        ),
    ]
