# Generated by Django 4.1.4 on 2023-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_prescription_medicine_prescription_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(blank=True, null=True, related_name='prescriptions', to='accounts.medicine'),
        ),
    ]
